### ISSUE TITLE
Intercom PHP API — v4.0.0 upgrade

### ISSUE THREAD

**Issue by jackwh** [slaughter550/intercom-laravel#4]
Are there plans to upgrade this package to use v4.0.0 of the Intercom PHP API?

See https://github.com/intercom/intercom-php/releases

Thanks in advance!

**Comment by slaughter550** [comment]
@JackWH Yes there is. I'm finally starting to have free time again and I'll be doing some spring upgrades soon!

Thanks for the interest & suggestion

**Comment by jackwh** [comment]
@slaughter550 Thanks! I'll close this issue, as I've added further comments under PR #5
